apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-scripts
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  post_reconfigure_script: |
{{ default "" .Values.postReconfigureScript | indent 4 }}
