{{- $postReconfigureScript := include "gitlab.postReconfigureScript" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "gitlab.fullname" . }}-scripts
  labels:
    app: {{ template "gitlab.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  post_reconfigure_script: |
{{ $postReconfigureScript | indent 4 }}
