image: registry.gitlab.com/charts/alpine-helm

before_script:
  - helm init || echo Ignoring error

lint:
  stage: test
  script:
    - helm lint charts/*

pages:
  stage: deploy
  script:
    - mkdir .public
    - (cd .public; for dir in ../charts/*; do helm package ../charts/$dir; done)
    - helm repo index .public --url https://charts.gitlab.io
    - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master
