pages:
  stage: deploy
  script:
  - mkdir .public
  - (cd .public; for dir in ../charts/*; do helm package ../charts/$dir; done)
  - helm repo index .public --url https://charts.gitlab.io
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master
