pages:
  image: alpine
  stage: deploy
  before_script:
    - apk update
    - apk add curl
    - curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash
  script:
    - mkdir .public
    - (cd .public; for dir in ../charts/*; do ../helm package ../charts/$dir; done)
    - ./helm repo index .public --url https://charts.gitlab.io
    - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master
