image: registry.gitlab.com/charts/alpine-helm

before_script:
  - helm init --client-only

lint:
  stage: test
  script:
    - helm lint charts/*

pages:
  stage: deploy
  script:
    - mkdir .public
    - (cd .public; helm package ../charts/*)
    - helm dep up charts/*
    - helm repo index .public --url https://charts.gitlab.io
    - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master
