apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{- if default "" .Values.gitlabRootPassword }}
  # Defaulting to a non-sensical value to silence b64enc warning. We'll never
  # actually use this default due to the if statement.
  gitlab-root-password: {{ default "ignore" .Values.gitlabRootPassword | b64enc | quote }}
  {{ end }}
  db-user: {{ template "encodeDbUsername" . }}
  db-password: {{ template "encodeDbPassword" . }}
  redis-password: {{ template "encodeRedisPassword" . }}
