apiVersion: v1
description: GitLab running on Kubernetes suitable for demos
name: gitlab-omnibus
version: 0.1.30
tillerVersion: ">=2.5.0"
keywords:
- git
- ci
- cd
- deploy
- issue tracker
- code review
- wiki
home: https://about.gitlab.com
sources:
- http://docs.gitlab.com/ce/install/kubernetes/
- https://gitlab.com/charts/charts.gitlab.io
icon: https://gitlab.com/uploads/group/avatar/6543/gitlab-logo-square.png
maintainers:
- name: GitLab Inc.
  email: support@gitlab.com
- name: Mark Pundsack
- name: Jason Plum
- name: DJ Mountney
- name: Joshua Lambert
