{{- if .Values.fastStorageEnabled }}
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: fast
  namespace: gitlab
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
  labels:
    kubernetes.io/cluster-service: "true"
provisioner: kubernetes.io/azure-disk
parameters:
  skuName: Premium_LRS
  location: eastus
  storageAccount: gitlabstorage
{{- end }}
