{{- if .Values.postgresDedicatedStorage }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-postgresql-storage
  namespace: gitlab
  {{- if or (eq .Values.provider "gke") (eq .Values.provider "acs") }}
  annotations:
    volume.beta.kubernetes.io/storage-class: fast
  {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresStorageSize }}
{{- end }}
