# Default values for kubernetes-gitlab-demo.
# This is a YAML-formatted file.

# Required variables
# baseIP is an externally provisioned static IP address that you must provide
#baseIP: 1.1.1.1

# baseDomain is the top-most part of the domain. Subdomains will be generated
# for gitlab, mattermost, registry, and prometheus.
# Recommended to set up an A record on the DNS to *.your-domain.com to point to
# the baseIP
# e.g. *.your-domain.com.	A	300	baseIP
#baseDomain: your-domain.com

# legoEmail is a valid email address used by Let's Encrypt. It does not have to
# be at the baseDomain.
#legoEmail: you@example.com

# Optional variables
gitlabNamespace: gitlab
# `ce` or `ee`
gitlab: ce
gitlabCEImage: gitlab/gitlab-ce:9.0.5-ce.0
gitlabEEImage: gitlab/gitlab-ee:9.0.5-ee.0
postgresPassword: NDl1ZjNtenMxcWR6NXZnbw==
initialSharedRunnersRegistrationToken: "tQtCbx5UZy_ByS7FyzUH"
mattermostAppSecret: NDl1ZjNtenMxcWR6NXZnbw==
mattermostAppUID: aadas
redisImage: redis:3.2.4
redisDedicatedStorage: true
redisStorageSize: 5Gi
postgresImage: postgres:9.6.1
# If you disable postgresDedicatedStorage, you should consider bumping up gitlabRailsStorageSize
postgresDedicatedStorage: true
postgresStorageSize: 30Gi
gitlabRailsStorageSize: 30Gi
gitlabRegistryStorageSize: 30Gi
gitlabConfigStorageSize: 1Gi
gitlabRunnerImage: gitlab/gitlab-runner:alpine-v9.0.2
# Valid values for provider are `gke` and `acs` for Google Container Engine and Azure Container Service respetively. Leaving it blank will disable fast disk options.
provider: gke
# acsStorageLocation is only used when provider=acs
acsStorageLocation: northcentralus
healthCheckToken: 'SXBAQichEJasbtDSygrD'
# Optional, for GitLab EE images only
#gitlabEELicense: base64-encoded-license

gitlab-runner:
  checkInterval: 1
  # gitlabUrl: https://gitlab.example.com
  # runnerRegistrationToken must equal initialSharedRunnersRegistrationToken
  runnerRegistrationToken: "tQtCbx5UZy_ByS7FyzUH"
  namespace: gitlab
  resources:
    limits:
      memory: 500Mi
      cpu: 600m
    requests:
      memory: 500Mi
      cpu: 600m
  runners:
    namespace: gitlab
    privileged: true
