apiVersion: v1
description: A bundle of GitLab CE, GitLab Runner, nginx-ingress, kube-lego
name: gitlab-bundle
version: 0.1.0
keywords:
- git
- ci
- cd
- deploy
- issue tracker
- code review
- wiki
home: https://about.gitlab.com
sources:
- https://hub.docker.com/r/gitlab/gitlab-ce/
- https://docs.gitlab.com/omnibus/
icon: https://gitlab.com/uploads/group/avatar/6543/gitlab-logo-square.png
maintainers:
- name: GitLab Inc.
  email: support@gitlab.com
- name: DJ Mountney
- name: Mark Pundsack
