apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-config
  namespace: gitlab
data:
  external_scheme: https
  external_hostname: gitlab.{{ .Values.baseDomain }}
  registry_external_scheme: https
  registry_external_hostname: registry.{{ .Values.baseDomain }}
  mattermost_external_scheme: https
  mattermost_external_hostname: mattermost.{{ .Values.baseDomain }}
  mattermost_app_uid: {{ .Values.mattermostAppUID }}
  postgres_user: gitlab
  postgres_db: gitlab_production
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-secrets
  namespace: gitlab
data:
  postgres_password: {{ .Values.postgresPassword }}
  initial_shared_runners_registration_token: {{ .Values.initialSharedRunnersRegistrationToken }}
  mattermost_app_secret: {{ .Values.mattermostAppSecret }}
