apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ciEnvironmentSlug }}
  labels:
    app: {{ .Values.ciEnvironmentSlug }}
    pipeline_id: {{ .Values.ciPipelineID }}
    build_id: {{ .Values.ciBuildID }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  #type: {{ .Values.service.type }}
  ports:
  - name: {{ .Values.service.name }}
    port: {{ .Values.service.internalPort }}
    targetPort: {{ .Values.service.name }}
    #protocol: TCP
  selector:
    name: {{ .Values.ciEnvironmentSlug }}
